cep:
  valido: 09520010/json
  campos: [
    "cep",
    "logradouro",
    "complemento",
    "bairro",
    "localidade",
    "uf",
    "unidade",
    "ibge",
    "gia"
]
  resultado: [
    "09520-010",
    "Rua João Pessoa",
    "lado ímpar",
    "Centro",
    "São Caetano do Sul",
    "SP",
    "",
    "3548807",
    "6361"
]
  inexistente: 01101011/json
  letras: asda10ee/json
  menos_numeros: 1234/json
  mais_numeros: 32113231231132323144543/json
  caracter_especial: 1234567$/json
  branco: /json
  teste: viacep.com.br/ws/RS/Porto Alegre/Domingos/json/ 